### PR TITLE
Add option to add "implicit" custom validation rules.

### PR DESCRIPTION
**Pull request by lorenzodalaqua**
Hello,

First of all, great work with this library, it's made my life validating forms both server and client side a whole lot easier.

Since my goal is to use the same rules both server and client side there is only one feature I missed from Laravel's validator, which is the possibility to add what they call "Implicit rules" (it's in the docs at [https://laravel.com/docs/5.4/validation](https://laravel.com/docs/5.4/validation) under "Implicit Extensions", but it's basically custom rules which are run even when the attribute is null, undefined or empty).

I noticed you already had implemented the default implicit rules in your code, so I took the liberty to add a registerImplicit function which besides registering the rule adds it to the implicitRules array. Seems simple enough, and I tried to keep to the same API that was being used by registerAsync, and also added the same function for async rules.

As can be seen in the commit history, my first approach was to add an "implicit" argument to the register function, but to mirror Laravel Validator's API I thought separate functions was the way to go.

Anyway, I'll wait for feedback :)

I hope it can be merged and I'll be able to stop using my fork because I need these implicit rules.

### CODE REVIEW

**Comment by mikeerickson** [comment]
@lordalaqua Thank you for this PR, it has been on the backlog for quite some time so this is a welcome addition.   If you wouldn't mind, can you please create an associated test to cover this PR and submit an update.

Thanks in advance...

**Comment by lorenzodalaqua** [comment]
Hi, I have added the tests as asked, I took a brief look over the existing tests and tried to follow them. I kept it minimal to try test only the "implicit" feature, that is, if the rules are checked when the value is undefined or null, so please let me know if you think these tests are enough or if there is anything else I can do. Glad to be of help :)

**Comment by lorenzodalaqua** [comment]
Any update on this?

**Comment by mikeerickson** [comment]
@lordalaqua Sorry for delay, I will have a look at this a bit later today and act accordingly.

**Comment by mikeerickson** [comment]
@lordalaqua Just merged, thanks for the PR :-)

**Comment by lorenzodalaqua** [comment]
Awesome, glad it was ok :smile: Thanks for the great work on the library!

**Comment by alanhr** [comment]
Hi @lordalaqua  and @mikeerickson,
This new implementation was not added in the documentation

**Comment by iamdtang** [comment]
@alanhr want to add it for us? :)

**Comment by mikeerickson** [comment]
@alanhr Thanks for information, I will get it added in due time :-) 

In the meantime, if you are keep to post a PR, it will gladly be accepted!

**Pull request merged**
