### PR TITLE
Add Greek (el) localization

### PR DESCRIPTION
**Pull request by Almis90**
Got the translation from https://github.com/caouecs/Laravel-lang/blob/master/src/el/validation.php, the only change I made is to `def`.

### CODE REVIEW

**Comment by iamdtang** [comment]
Thanks @Almis90 ! Could you please update the Gruntfile? https://github.com/skaterdav85/validatorjs/blob/master/Gruntfile.js

**Comment by Almis90** [comment]
Hello @skaterdav85 sorry for late response. I don't know how I can add the change to existing (this one) pull, can you help me with that? I commited the change on my clone what to I do next?

**Comment by iamdtang** [comment]
Just make another commit on this same branch and push. :)

**Comment by Almis90** [comment]
Okay done, my mistake was that I was commiting on master and not on patch-1 :)

**Comment by iamdtang** [comment]
Thanks @Almis90! Released in 3.8.0.

**Pull request merged**
