### PR TITLE
Added a German translation file

### PR DESCRIPTION
**Pull request by boris-glumpler**

### CODE REVIEW

**Comment by iamdtang** [comment]
Thanks @shabushabu! Released in version 3.3.0.

**Comment by boris-glumpler** [comment]
Thanks, mate!

**Comment by boris-glumpler** [comment]
Switching to German doesn't actually work right now. I think it looks in the `dist/lang` folder, but I only added it to the `src/lang` folder. Is there a build script that still needs to get run maybe?

**Comment by iamdtang** [comment]
@shabushabu Ah yes it was the Grunt file. I fixed it and published in 3.3.1

**Comment by boris-glumpler** [comment]
Great, cheers!

**Pull request merged**
