### PR TITLE
Add finnish translations

### PR DESCRIPTION
**Pull request by duubliduu**

### CODE REVIEW

**Comment by jonnetanninen** [comment]
Any change for this to get approved & merged? Would need this in production soon...

**Comment by vict-shevchenko** [comment]
Hi, you also need to update a `Gruntfile.js`

**Comment by duubliduu** [comment]
`Gruntfile.js` is now updated!

**Comment by mikeerickson** [comment]
@duubliduu thank you for the PR, it has been merged.  I will work on getting a new build published to npm over the weekend

**Pull request merged**
