### PR TITLE
Added wildcard search 

### PR DESCRIPTION
**Pull request by bricox**
I've added wildcard searching.  I made most of the changes in the validator._parseRules function in order to be able to generate the rules based on the property paths for the attribute and the rules; particularly around the required_if rules.  

So, given the object
{ id: 2, 
   addresses:[
      {street: "", city:"Nashville", requireStreet: true },
      {street: "", city:"Nashville", requireStreet: false }
]}

and the validation rule:

{
"addresses._.street: required_if:addresses._.street.requiredStreet,true"
}

The following rules are what are actually applied.

{
"addresses.0.street: required_if:addresses.0.street.requiredStreet,true",
"addresses.1.street: required_if:addresses.1.street.requiredStreet,true"
}

Thanks,
Brian

### CODE REVIEW

**Comment by iamdtang** [comment]
@bricox Thanks! Could you also update the README? You can base it off of Laravel's documentation, or just copy it if it behaves the same way.

@garygreen @LKay Want to also review?

**Comment by bricox** [comment]
Yes, I'll update the readme.  I also plan to add documentation about the required_if option.  I believe that is missing from the readme right now.

**Comment by iamdtang** [comment]
@bricox cool thanks let me know when that is done.

**Comment by LKay** [comment]
Looks fine, I guess.

Btw. What about this typescript rewrites code I put a while ago?

**Comment by iamdtang** [comment]
@LKay I'll address it [in that issue](https://github.com/skaterdav85/validatorjs/issues/106).

**Comment by iamdtang** [comment]
@bricox any update?

**Comment by itaylorweb** [comment]
@skaterdav85 Has this been implemented?  Desperately need validation on array objects. :)

**Comment by alanhr** [comment]
Hi guys, this idea died?

**Comment by mikeerickson** [comment]
@alanhr Looks like there are some merge conflicts.   If you could cure them and make sure all tests pass (as well as adding any tests which support your work), I will have a look and merge accordingly.

**Comment by alanhr** [comment]
ok @mikeerickson,  I'll try solve these problems and to do more tests

**Comment by blacktrue** [comment]
Hi

This has some progress ? It's really necessary

Thanks

**Comment by alanhr** [comment]
hi @blacktrue ,
Today I was done  this PR #190 with these fix

**Pull request closed without merging**
