### PR TITLE
Add date rule

### LINKED ISSUE #93: Add `date` rule
The date rule is commonly used in many implementations and should come with default available rules set. It should be valid for any format that applies to javascript `Date` object constructor epoch, ISO etc.

### PR DESCRIPTION
**Pull request by LKay**
Adds basic `date` rule. Anything that can be parsed as valid date by javascript `Date` object is treated as valid date.

Resolves #93.

### CODE REVIEW

**Comment by iamdtang** [comment]
I think before this is merged, we need a way to ensure that any new rules we introduce don't break any custom rules that users define so that we follow semver. For example, if someone created a custom `date` rule, that would take precedence over this one. Want to add that feature? Once we have that, then this PR can get merged.

**Comment by LKay** [comment]
I started rewriting this here https://github.com/LKay/validatorjs/tree/lkay/typescript-rewrite and I will make sure that rules could could be overriden. For current code this feature might be quite troublesome.

**Comment by iamdtang** [comment]
Actually, it looks custom rules override the built-in ones already. My mistake. Thanks for the help!

**Comment by iamdtang** [comment]
Released in 3.1.0

**Pull request merged**
