### PR TITLE
add basic support for gt, gte, lt and lte

### PR DESCRIPTION
**Pull request by patrick-radius**

### CODE REVIEW

**Comment by mikeerickson** [comment]
@patrick-radius Thank you for the contribution.  Currently, this project is on a feature freeze as it is going under a clean sweep as we move to version 4.0   I will keep this PR open and integrate functionality into the new code base.

**Comment by patrick-radius** [comment]
Thanks.
In that case I (and I assume others) would appreciate a branch with the 4.0.0 code to target PRs and maybe use and contribute to.

Good work!

**Comment by mikeerickson** [comment]
It will be posted as soon as it is ready for public consumption 🤓

**Comment by patrick-radius** [comment]
Thanks for your reply.
Don't get me wrong: I don't want to pressure you.

But if you could do the development publicly in a separate branch I and a lot of other people can help and, while understanding the risks, use it.
Also we will be able to see the direction of the rewrite and determine if we want to wait for that in new projects or find an alternative solution for validation.

**Comment by mikeerickson** [comment]
I totally understand, and like I said I will surely solicit help when it is more mature (it is being rewritten in TypeScript), so quite a bit of nuts and bolts refactoring need to be finalized.

**Comment by vict-shevchenko** [comment]
It's very right choice Mike! My product [reactive-mobx-form](https://github.com/vict-shevchenko/reactive-mobx-form) heavily relays on validatorjs, so I am open for help.

**Pull request closed without merging**
