### PR TITLE
Basic usages import statement code fixed

### PR DESCRIPTION
**Pull request by asifsaho**

### CODE REVIEW

**Comment by vict-shevchenko** [comment]
This is a syntax of how optional parameters are described.

Like here [Array splice](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/splice)

I don`t think this requires any change.

**Comment by vict-shevchenko** [comment]
@mikeerickson can you please close this PR?

**Comment by mikeerickson** [comment]
@vict-shevchenko Thanks for PR 👍

**Comment by vict-shevchenko** [comment]
@mikeerickson sorry, under close I mean reject and close. As code in provided PR is incorrect. When we want to soecify optional parameters comma should be inside [].  
This was not my PR actually ))

**Pull request merged**
