### PR TITLE
Comprehensive regex for URL validation

### PR DESCRIPTION
**Pull request by tsriram**
Not sure if I'm supposed to include files changed in `dist/`. Have included them anyway.

Closes skaterdav85/validatorjs#182

### CODE REVIEW

**Comment by mikeerickson** [comment]
No, you don't include./dist as they are built via build process.  

Also, if you could please add necessary tests, that would be appreciated.  I will check back on this over weekend.  

Thanks for PR, just need to include tests

**Comment by tsriram** [comment]
Cool, should I then add `dist` to `.gitignore`? Have already added a new test and modified an existing test for the changes. See if they're okay.

Edit: I'll just remove dist files from commit and don't bother about .gitignore for now.

**Comment by iamdtang** [comment]
@mikeerickson maybe we should stop tracking the /dist folder. I originally left it in the repo so that people could copy the script from there if they weren't familiar with Git, Bower, etc. Now I think everyone is accustomed to those tools. What do you think?

**Comment by mikeerickson** [comment]
@skaterdav85 I think that is a great idea.  I can make the change and update documentation for those rare cases when someone would need the built items

**Comment by iamdtang** [comment]
@mikeerickson that'd be great! thanks!

**Pull request merged**
