### PR TITLE
Ip validation

### PR DESCRIPTION
**Pull request by CSenshi**
Following patch implements validation of IPv4 and IPv6, mentioned in following issue #365.

source code Implemented 3 rules:
'ipv4' - validates IPv4
'ipv6' - validates IPv6
'ip' - validates both

tests are written in ip.js.

### CODE REVIEW

**Comment by CSenshi** [comment]
Hello, I think Travis-CI and Github communication is kinda bugged. On [Travis](https://travis-ci.org/github/skaterdav85/validatorjs/builds/680737346) you can see that my PR passed all checks, but here it shows that "Some checks haven’t completed yet"

**Comment by iamdtang** [comment]
Hmmm, does making another commit fix it? What do you think @mikeerickson? If this does look good, it'd probably be good if you rebased into a single commit.

**Comment by mikeerickson** [comment]
@CSenshi There were some issues with Travis that is keeping this from passing PR submission.  However, I am going to take in this code manually and make it available in the next ValidatorJS update.

Thank you for the contribution

**Comment by mikeerickson** [comment]
@CSenshi This has been added to the forthcoming 3.19 release (should be published tomorrow)

**Pull request closed without merging**
