### PR TITLE
Update languages

### PR DESCRIPTION
**Pull request by Ragelyte**
Added new languages from https://github.com/caouecs/Laravel-lang and updated code style

### CODE REVIEW

**Comment by vict-shevchenko** [comment]
Hi @Ragelyte 
what I see is that you missed updating a Gruntfile.js for new languages.

@mikeerickson Mike, I suppose we still have the behaviour that when bundling with webpack all languages are included into a final bundle.js?

**Comment by mikeerickson** [comment]
@Ragelyte As @vict-shevchenko has mentioned, this PR is indeed missing the Gruntfile update to include the new language.  If you could please make these changes and assure CI passes, I will move forward getting this PR merged.

@vict-shevchenko Yes, you are indeed correct.  When using the default require(import) it will include all languages.  Admittedly, this is not ideal and it produces a rather "large" bundle.  Other projects such as Momemt.js have this similar issue and there are alternatives available (ie letting developer determine which languages he/she wants to support)

**Comment by Ragelyte** [comment]
@vict-shevchenko @mikeerickson  the  Gruntfile.js is now updated

**Review by mikeerickson — COMMENTED** [review]
Why so many changes to this file, we have used the same format for many years for this project.  It seems you have reworked the flow of the document, and applied your own style for formatting.

**Review by mikeerickson — CHANGES_REQUESTED** [review]
I am not inclined to merge such a PR with these edits which is primarily related to formatting and style preferences.  If you can adjust the PR to retain all the original formatting of files which are not related to your changes, and make sure your additions follow the same styling, I will be happy to include the new language addition.  

As it is, there are just way too many files which have been edited that don’t relate to core of you changes.

**Comment by Ragelyte** [comment]
Hi @mikeerickson,

The code style changed due automatic linting by IDE.

I have now reverted the style changes and set the spacings to 2-characters. Also, reverted all the style changes to non-language files too.

And ran grunt task to generate dist.

Would be good to setup a CI linter for codestyle.

**Comment by mikeerickson** [comment]
Agreed, I have have actually created a todo for myself to take care of this.  I was actually surprised to see it wasn’t already there. 

I will review this full PR tomorrow and get it merged if all is good.  Thanks for your submission.

**Comment by mikeerickson** [comment]
@Ragelyte Thank you for your contribution, all looks good now.

**Pull request merged**
