### PR TITLE
Browserify and test improvements, run on node and browser

### PR DESCRIPTION
**Pull request by garygreen**
Ready to merge.

### CODE REVIEW

**Comment by iamdtang** [comment]
Hmm. What if we provide different builds for each language and then provide a way where users can override the default messages? With different builds, we dont have to worry about dynamic loading between environments at all.

**Comment by garygreen** [comment]
That could be an option but personally I'd prefer to find a way of being able to just include the languages you want to support. In the browser that means just including in `<script>` that language file and it will automatically be loaded, then just set the language you want to use `Validator.setLang('ru')`.

This PR is almost ready, works perfectly in node but just needs a bit of tweaking to get it working in the browser.

**Comment by garygreen** [comment]
I think I've find a nice way to do it, just working out a few kinks.

**Comment by garygreen** [comment]
@skaterdav85 christmas has come early ! Tests all passing, looks all good to merge now buddy.

With this PR:
- Originally just the browser version was being tested, now it tests both node and browser.
- Uses the actual source files when in node and doesn't need the dist at all.
- Automatically picks up on languages both in browser and node:
  - In node, to use russian: `var Validator = require('validatorjs'); Validator.setLang('ru');` done.
  - In browser, include russian language: `<script src="validatorjs/dist/lang/ru.js"></script>` and `Validator.setLang('ru');` done.

**Pull request merged**
