### PR TITLE
Add object rule define

### PR DESCRIPTION
**Pull request by zamarawka**
Type checking validation

```js
var validation = new Validator({
	age: 30,
	name: ''
}, {
	age: ['required', { 'in': [29, 30] }],
	name: [{ required_if: ['age', 30] }]
});

validation.fails(); // true
validation.passes(); // false

```

### CODE REVIEW

**Comment by mikeerickson** [comment]
@zamarawka Can you please update (add) tests to support this PR.   Further, please make sure it works in both nodejs and browser.

**Comment by zamarawka** [comment]
@mikeerickson tests at commit d1a7dc5
Bundle are builded and all tests passed at 038ae48 and this branch already used in my private project.

**Comment by mikeerickson** [comment]
@zamarawka Thank you very much, I will have a look at this and get it merged in asap.  Thx for the PR ;->

**Comment by mikeerickson** [comment]
@zamarawka Thanks for your efforts.  This PR will be available in next release

**Pull request merged**
