### PR TITLE
add sometimes feature including tests

### PR DESCRIPTION
**Pull request by richriscunha**
#69

### CODE REVIEW

**Comment by iamdtang** [comment]
on vacation. will check this in a week.

**Comment by garygreen** [comment]
@richriscunha thanks for this PR. Just one thing, could you also add the:

``` js
if (this._passesOptionalCheck(attributeRules) && !(this._suppliedWithData(attribute))) { continue; }
```

to the `checkAsync` method as well? Bit funny that there are two check methods but one is to handle async-based validation.

**Comment by richriscunha** [comment]
Sure, I'm traveling on business now. So, I won't get to it until at least the middle to end of the week.  But, if I can get to it sooner, I will.

**Comment by richriscunha** [comment]
@garygreen I've added the additional check to the checkAsync method now too.  In addition, I've added a couple of more test specs to cover checkAsync using the **_sometimes_** rule too.

**Pull request merged**
